# syntax=docker/dockerfile:1.4
FROM python:3.10

WORKDIR /root

# Create and activate virtual environment
ENV VIRTUAL_ENV="/root/.venv"
RUN python3.10 -m venv "$VIRTUAL_ENV"
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# start the backend
COPY ./requirements.txt .

# Install package
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# add entrypoint.sh
# COPY entrypoint.sh .
# RUN chmod +x entrypoint.sh

COPY . .

EXPOSE 5001

CMD ["flask", "run", "--host=0.0.0.0", "--port=5001"]

