services:

  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    env_file:
      - ./local.env

  backend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 5001:5001
    depends_on:
      - database

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 8888:8888
